languageCode = "en"
languageName = "English"
title = "Pellucid Resonance"
weight = 2

[params]
  description = "Something, once quiet, remains."
  omitCategoryOnMenu = false
  categoryName = "Category"
